version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9091:9090'

  flink-jobmanager:
    image: flink:latest
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager

  flink-taskmanager:
    image: flink:latest
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 4

  chainbase-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chainbase-node
    ports:
      - '8080:8080'
    volumes:
      - ${OPERATOR_CONFIG_PATH:-./operator.yaml}:/opt/operator.yaml
      - ${EIGEN_KEY_PATH:-./eigen-test.ecdsa.key.json}:/opt/eigen-test.ecdsa.key.json
      - ${AVS_CONFIG_PATH:-./avs.toml}:/root/avs.toml
    environment:
      - OPERATOR_CONFIG_PATH=${OPERATOR_CONFIG_PATH:-./operator.yaml}
      - EIGEN_KEY_PATH=${EIGEN_KEY_PATH:-./eigen-test.ecdsa.key.json}
      - AVS_CONFIG_PATH=${AVS_CONFIG_PATH:-./avs.toml}
    depends_on:
      - prometheus
      - flink-jobmanager
      - flink-taskmanager
